### ISSUE TITLE
Add support for `merge` incremental strategy

### ISSUE THREAD

**Issue by hovaesco** [starburstdata/dbt-trino#105]
### Describe the feature

Recently, Trino added support for `MERGE` statement https://trino.io/docs/current/sql/merge.html
dbt-trino can now benefit from it by adding `merge` incremental strategy.

**Comment by antiqe** [comment]
Exactly what's we were waiting for 💯 Thanks a lot @hovaesco 

Trino 393 open the gate.

**Comment by hovaesco** [comment]
Resolved by https://github.com/starburstdata/dbt-trino/pull/104

**Comment by sumanshusamarora** [comment]
Hi @hovaesco , 

Seems like you have got trino working with DBT. I am setting up dbt trino with azure data lake as storage and glue as metastore. I have tried using both hive connector and delta lake connector but got blocked on both approaches as below.
Delta Lake - DBT creates the table as expected but can't read the table back. It throws errors UNSUPORRTED_TABLE_TYPE
Hive - Can't make incremental models work due to tables being non-transactional. And incremental strategy expects the table to allow ACID transactions. Could you please help!
