### ISSUE TITLE
v1.0.3 pinned to dbt-core==1.0.3

### ISSUE THREAD

**Issue by colin-rogers-dbt** [starburstdata/dbt-trino#221]
### Expected behavior

dbt-trino is compatible with the latest <major>.<minor> patch version of dbt-core (i.e. it uses `dbt-core ~= 1.0.0` syntax in expressing requirements in it's `setup.py` file)

### Actual behavior

[setup.py](https://github.com/starburstdata/dbt-trino/blob/v1.0.3/setup.py#L62) in v1.0.3 pins to earlier 1.0 patch of dbt-core making it incompatible with later patch releases. The result is an unexpected downgrade from `dbt-core==1.0.9`-> `dbt-core==1.03`.

### Steps To Reproduce

pip install dbt-core~=1.0.0 dbt-trino~=1.0.0

### Operating System

linux

### dbt version

1.0.9

### Trino Server version

N/A

### Python version

3.9

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by leniartek** [comment]
Hi @colin-rogers-dbt
Issue is already fixed for dbt-core 1.1
dbt-core 1.0.x is not supported anymore, that's why I don't see a reason to fix this.

https://docs.getdbt.com/docs/dbt-versions/core
<img width="1003" alt="Screenshot 2023-02-02 at 12 02 04" src="https://user-images.githubusercontent.com/10237525/216308952-1c64e541-803f-4910-9d6b-9e45ccddbaf1.png">

**Comment by leniartek** [comment]
@colin-rogers-dbt We will fix this issue in order to clear the path for the future backports.
