### ISSUE TITLE
'dbt docs generate' command doesn't create sources block in catalog.json file

### ISSUE THREAD

**Issue by ozhanridvan** [starburstdata/dbt-trino#228]
### Expected behavior

i have 1 simple model and schema.yml file connected to it. when i run the 'dbt docs generate', i am expecting to dbt write all the informations (table&column descriptions, tests etc.) in the schema.yml/sources block to the target/catalog.json file. 

### Actual behavior

it doesnt work. sources block in the target/catalog.json file is an empty dictionary.

### Steps To Reproduce

1 model with {{source}} function, schema.yml with sources block would be enough.

### Log output/Screenshots

![image](https://user-images.githubusercontent.com/82097374/217538344-fe1818c0-7265-4e4a-9fc8-3d9c9a156cb4.png)
![Screenshot_5](https://user-images.githubusercontent.com/82097374/217538526-444473b2-5b9a-4655-bb12-706913b96184.png)

### Operating System

Ubuntu 22.04.1 LTS

### dbt version

dbt-core: 1.4.0 / trino:1.4.0

### Trino Server version

402

### Python version

3.10.6

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
Sources should be present under the `nodes` field. Not sure why dbt core still has the empty sources field (maybe for backwards compatibiltiy

However sources are not present because the metadata is not retrieved through the get_catalog macro because this information is not passed as paramenter (only schemas are passed)

This is rather a dbt core issue. It seems that dbt core assumes a single database/catalog setup here. Can you raise this issue on dbt-core repo?
